---
apiVersion: v1
kind: ConfigMap
metadata:
 name: telegraf-config
 namespace: telegraf
data:
 telegraf.conf: |
  [global_tags]
  # Add any global tags here
  [agent]
  interval = "10s" # Adjust the interval as per your requirements
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = true

  # # Retrieves SNMP values from remote agents
  [[inputs.snmp]]
  #   ## Agent addresses to retrieve values from.
  #   ##   format:  agents = ["<scheme://><hostname>:<port>"]
  #   ##   scheme:  optional, either udp, udp4, udp6, tcp, tcp4, tcp6. Default is udp
  #   ##   port:    optional
     #agents = []
     interval = "1m"
     timeout = "5s"
     version = 2
     #community=""


   [[inputs.snmp.field]]
    name = "hostname"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true
   
   [[inputs.snmp.tags]]
    site = ""
    network = ""
   
   [[inputs.snmp.field]]
     name = "uptime"
     oid = "RFC1213-MIB::sysUpTime.0"

   [[inputs.snmp.field]]
     name = "cpu"
     oid = ".1.3.6.1.4.1.2021.11.10.0"

   [[inputs.snmp.field]]
     name = "total_mem"
     oid = ".1.3.6.1.4.1.2021.4.5.0"

   [[inputs.snmp.field]]
     name = "mem_used"
     oid = ".1.3.6.1.4.1.2021.4.6.0"

   [[inputs.snmp.field]]
     name = "5min_load"
     oid = ".1.3.6.1.4.1.2021.10.1.3.2"

   [[inputs.snmp.field]]
     name = "15min_loaad"
     oid = ".1.3.6.1.4.1.2021.10.1.3.3"

   [[inputs.snmp.table]]
     oid = "IF-MIB::ifTable"
     name = "interface"
     inherit_tags = ["hostname"]

   [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifDescr"
      name = "ifDescr"
      is_tag = true

   [[inputs.snmp.table]]
    name = "hrStorage"
    oid = ".1.3.6.1.2.1.25.2.3"
    inherit_tags = ["hostname"]

   [[inputs.snmp.table.field]]
    name = "hrStorageDescr"
    oid = "HOST-RESOURCES-MIB::hrStorageDescr"
    is_tag = true

  [[inputs.snmp_trap]]
   service_address = "udp://localhost:5162"
   timeout = "10s"

  #[[outputs.influxdb_v2]]
  #urls = [""]
  #token = ""
  #organization = ""
  #bucket = ""

  [[outputs.syslog]]
  address = "tcp://ip-address:port"



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: telegraf
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf:latest # Replace with the Telegraf image name and version
          volumeMounts:
            - name: config-volume
              mountPath: /etc/telegraf
            - name: mibs
              mountPath: /usr/share/snmp
      volumes:
        - name: config-volume
          configMap:
            name: telegraf-config
        - name: mibs
          hostPath:
            path: {path_to_snmp_monitoring}/snmp_monitoring/telgraf/snmp
